version: "3"

services:
  pubsub:
    image: messagebird/gcloud-pubsub-emulator:latest
    ports:
      - "8333:8681"
    environment:
      - PUBSUB_PROJECT1=emulator,sender:sender
    volumes:
      - /data

  tests:
    build: .
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
      - PUBSUB_PROJECT_ID=emulator
    volumes:
      - ./:/tmp/testresults.host
    depends_on:
      - pubsub