version: "3"

services:
  pubsub:
    image: messagebird/gcloud-pubsub-emulator:latest
    ports:
      - "8333:8681"
    environment:
      - PUBSUB_PROJECT1=emulator
    volumes:
      - /data

  tests:
    build: .
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
      - PUBSUB_PROJECT_ID=emulator
    volumes:
      - ./:/tmp/testresults.host
    command:
      - /bin/sh
      - -c
      - |
        sleep 10 && \
        dotnet test --collect:"XPlat Code Coverage" --test-adapter-path:. \
        --logger:"junit;LogFilePath=/tmp/testresults.run/{assembly}-test-result.xml;MethodFormat==Class;FailureBodyFormat=Verbose" \
        --results-directory /tmp/testresults.run ; \
        mkdir -p /tmp/testresults.host/testreports && \
        cp -r /tmp/testresults.run/* /tmp/testresults.host/testreports/
    depends_on:
      - pubsub